// <auto-generated />
namespace CPOS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class producttobatchtraverse : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(producttobatchtraverse));
        
        string IMigrationMetadata.Id
        {
            get { return "202105010705106_producttobatchtraverse"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
